[package]
name = "ac-examples"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.2", features = ['derive'] }
env_logger = "0.10.0"
log = { version = "0.4.14" }
serde_json = { version = "1.0.79" }
tokio = { version = "1.24", features = ["rt-multi-thread", "macros", "time"] }
wabt = "0.10.0"

# Substrate dependencies
frame-support = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
frame-system = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
kitchensink-runtime = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
pallet-balances = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
pallet-identity = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
pallet-staking = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
sp-core = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
sp-keyring = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
sp-runtime = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }
sp-version = { git = "https://github.com/haerdib/substrate.git", branch = "add-serde-feature-to-primitives" }

# local deps
substrate-api-client = { path = "..", features = ["tungstenite-client", "ws-client", "staking-xt"] }
